version: "3"

services:
  server:
    build: "../server"
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      PORT: "${SERVER_PORT}"
    command: sh -c "yarn && yarn dev"
    volumes:
      - ../server:/usr/src/app

  ui:
    build: "../ui"
    ports:
      - "${UI_PORT}:${UI_PORT}"
    environment:
      PORT: "${UI_PORT}"
    command: sh -c "yarn && yarn dev"
    volumes:
      - ../ui:/usr/src/app

  db:
    image: postgres:11.1
    command: "-c logging_collector=on"
    restart: always
    ports:
      - "${PG_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_DB: ${PG_DB}

  adminer:
    image: adminer
    restart: always
    ports:
      - ${ADMINER_PORT}:8080
